stages:          # List of stages for jobs, and their order of execution
  - build
  - run_tests

build-test:       
  stage: build
  script:
    - echo "Compiling the testing code and setup lib"
    - echo "example: pip install, npm install...."
    - docker build -t python-gui-tests .

run-tests:
   stage: run_tests
   script:
    - docker run python-gui-tests



